export const CURRENCY = "PLN"
export const CURRENCY_VALUE = "zł"
export const ADMIN_EMAIL = "mateuszbizon2000@gmail.com"
export const PHONE_NUMBER = "+48 613 940 380"
export const EMAIL = "email@email.pl"
export const LOCATION = "ul. Ulicowa 59, 59-900 Zgorzelec"