import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";

export const jost = Jost({
  subsets: ["latin"],
  variable: "--font-jost",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body
        className={`${jost.className}`}
      >
        {children}
      </body>
    </html>
  );
}
